author = Ekkehart Schlicht
email = TVC@econ.lmu.de
version = 3.0
date = 2024-05-03
description = Regression with Time-varying coefficients (TVC)
tags = C22
min-version = 2023c
data-requirement = needs-time-series-data
public = TVCestimate getTVCcoeffs getTVCstderr plotTVC
gui-main = TVCestimate
label = Time-varying coefficients (TVC)
menu-attachment = MAINWIN/Model/TSModels
help = TVC.pdf
gui-help = TVC_help.md
sample-script = TVC_sample.inp
data-files = OkunGer.gdt
depends = TVCplots
