author = Ekkehart Schlicht
email = TVC@econ.lmu.de
version = 2.0
date = 2023-12-21
description = Regression with Time-varying coefficients (TVC)
tags = C22
min-version = 2023c
data-requirement = needs-time-series-data
gui-main = TVCestimate
label = Time-varying coefficients (TVC)
menu-attachment = MAINWIN/Model/TSModels
public = TVCestimate 
help = TVC.pdf
gui-help = TVC_help.md
sample-script = TVC_sample.inp
data-files = OkunGer.gdt
